use_frameworks!

platform :ios, '8.0'

target 'DJHttpServerTest_Example' do
  pod 'DJHttpServerTest', :path => '../'

  target 'DJHttpServerTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
